### ISSUE TITLE
Align white box to right, align red box to left

### ISSUE THREAD

**Issue by Saltssaumure** [Saltssaumure/pios-text-editor#2]
Just like in original ggroups. Perhaps add this as a toggle (classic vs vertical style).

**Comment by aybri** [comment]
Wait, shouldn't it be the other way around?

**Comment by Saltssaumure** [comment]
> Wait, shouldn't it be the other way around?

In ggroups, red text is on the left hand side. I suppose I could add the option for it to appear the other way round too.

**Comment by aybri** [comment]
> > Wait, shouldn't it be the other way around?
> 
> In ggroups, red text is on the left hand side. I suppose I could add the option for it to appear the other way round too.

K.

**Comment by aybri** [comment]
I fixed the issue in a fork I made, however you can't change the location of the boxes.
